# Generated by Django 5.0.7 on 2024-08-13 12:12

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_post_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.TextField()),
                ('date', models.DateField(verbose_name=datetime.datetime(2024, 8, 13, 13, 12, 40, 58670))),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='comment', to='blog_app.post')),
            ],
        ),
    ]
