# Generated by Django 5.0.7 on 2024-08-27 10:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_alter_comments_date_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.TextField(blank=True, max_length=35),
        ),
        migrations.AlterField(
            model_name='comments',
            name='date',
            field=models.DateField(verbose_name=datetime.datetime(2024, 8, 27, 11, 41, 12, 94354)),
        ),
    ]
